//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_OPI.wsSYS_LHTC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSYS_LHTC.wsSYSSoap")]
    public interface wsSYSSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadMOTypeProperty", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.LoadMOTypePropertyResponse LoadMOTypeProperty(DB_OPI.wsSYS_LHTC.LoadMOTypePropertyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMOTypeProperty", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.AddMOTypePropertyResponse AddMOTypeProperty(DB_OPI.wsSYS_LHTC.AddMOTypePropertyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditMOTypeProperty", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.EditMOTypePropertyResponse EditMOTypeProperty(DB_OPI.wsSYS_LHTC.EditMOTypePropertyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelMOTypeProperty", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.DelMOTypePropertyResponse DelMOTypeProperty(DB_OPI.wsSYS_LHTC.DelMOTypePropertyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApproveMOTypeProperty", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyResponse ApproveMOTypeProperty(DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadMOTypePropertyDefine", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineResponse LoadMOTypePropertyDefine(DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadMOTypeInventory", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryResponse LoadMOTypeInventory(DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMOTypeInventory", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.AddMOTypeInventoryResponse AddMOTypeInventory(DB_OPI.wsSYS_LHTC.AddMOTypeInventoryRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelMOTypeInventory", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.DelMOTypeInventoryResponse DelMOTypeInventory(DB_OPI.wsSYS_LHTC.DelMOTypeInventoryRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/funCheckDateTimeFormat", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatResponse funCheckDateTimeFormat(DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadFunctionPrinter", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.LoadFunctionPrinterResponse LoadFunctionPrinter(DB_OPI.wsSYS_LHTC.LoadFunctionPrinterRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadSystemFunction", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.LoadSystemFunctionResponse LoadSystemFunction(DB_OPI.wsSYS_LHTC.LoadSystemFunctionRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadCFGTERM", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.LoadCFGTERMResponse LoadCFGTERM(DB_OPI.wsSYS_LHTC.LoadCFGTERMRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCFGTERM", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.AddCFGTERMResponse AddCFGTERM(DB_OPI.wsSYS_LHTC.AddCFGTERMRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditCFGTERM", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.EditCFGTERMResponse EditCFGTERM(DB_OPI.wsSYS_LHTC.EditCFGTERMRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelCFGTERM", ReplyAction="*")]
        DB_OPI.wsSYS_LHTC.DelCFGTERMResponse DelCFGTERM(DB_OPI.wsSYS_LHTC.DelCFGTERMRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadMOTypePropertyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadMOTypeProperty", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadMOTypePropertyRequestBody Body;
        
        public LoadMOTypePropertyRequest() {
        }
        
        public LoadMOTypePropertyRequest(DB_OPI.wsSYS_LHTC.LoadMOTypePropertyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadMOTypePropertyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public LoadMOTypePropertyRequestBody() {
        }
        
        public LoadMOTypePropertyRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadMOTypePropertyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadMOTypePropertyResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadMOTypePropertyResponseBody Body;
        
        public LoadMOTypePropertyResponse() {
        }
        
        public LoadMOTypePropertyResponse(DB_OPI.wsSYS_LHTC.LoadMOTypePropertyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadMOTypePropertyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadMOTypePropertyResult;
        
        public LoadMOTypePropertyResponseBody() {
        }
        
        public LoadMOTypePropertyResponseBody(string LoadMOTypePropertyResult) {
            this.LoadMOTypePropertyResult = LoadMOTypePropertyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMOTypePropertyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMOTypeProperty", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.AddMOTypePropertyRequestBody Body;
        
        public AddMOTypePropertyRequest() {
        }
        
        public AddMOTypePropertyRequest(DB_OPI.wsSYS_LHTC.AddMOTypePropertyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMOTypePropertyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public AddMOTypePropertyRequestBody() {
        }
        
        public AddMOTypePropertyRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMOTypePropertyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMOTypePropertyResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.AddMOTypePropertyResponseBody Body;
        
        public AddMOTypePropertyResponse() {
        }
        
        public AddMOTypePropertyResponse(DB_OPI.wsSYS_LHTC.AddMOTypePropertyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMOTypePropertyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddMOTypePropertyResult;
        
        public AddMOTypePropertyResponseBody() {
        }
        
        public AddMOTypePropertyResponseBody(string AddMOTypePropertyResult) {
            this.AddMOTypePropertyResult = AddMOTypePropertyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditMOTypePropertyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditMOTypeProperty", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.EditMOTypePropertyRequestBody Body;
        
        public EditMOTypePropertyRequest() {
        }
        
        public EditMOTypePropertyRequest(DB_OPI.wsSYS_LHTC.EditMOTypePropertyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditMOTypePropertyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public EditMOTypePropertyRequestBody() {
        }
        
        public EditMOTypePropertyRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditMOTypePropertyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditMOTypePropertyResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.EditMOTypePropertyResponseBody Body;
        
        public EditMOTypePropertyResponse() {
        }
        
        public EditMOTypePropertyResponse(DB_OPI.wsSYS_LHTC.EditMOTypePropertyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditMOTypePropertyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditMOTypePropertyResult;
        
        public EditMOTypePropertyResponseBody() {
        }
        
        public EditMOTypePropertyResponseBody(string EditMOTypePropertyResult) {
            this.EditMOTypePropertyResult = EditMOTypePropertyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelMOTypePropertyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelMOTypeProperty", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.DelMOTypePropertyRequestBody Body;
        
        public DelMOTypePropertyRequest() {
        }
        
        public DelMOTypePropertyRequest(DB_OPI.wsSYS_LHTC.DelMOTypePropertyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelMOTypePropertyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public DelMOTypePropertyRequestBody() {
        }
        
        public DelMOTypePropertyRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelMOTypePropertyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelMOTypePropertyResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.DelMOTypePropertyResponseBody Body;
        
        public DelMOTypePropertyResponse() {
        }
        
        public DelMOTypePropertyResponse(DB_OPI.wsSYS_LHTC.DelMOTypePropertyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelMOTypePropertyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DelMOTypePropertyResult;
        
        public DelMOTypePropertyResponseBody() {
        }
        
        public DelMOTypePropertyResponseBody(string DelMOTypePropertyResult) {
            this.DelMOTypePropertyResult = DelMOTypePropertyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveMOTypePropertyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveMOTypeProperty", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyRequestBody Body;
        
        public ApproveMOTypePropertyRequest() {
        }
        
        public ApproveMOTypePropertyRequest(DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveMOTypePropertyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public ApproveMOTypePropertyRequestBody() {
        }
        
        public ApproveMOTypePropertyRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveMOTypePropertyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveMOTypePropertyResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyResponseBody Body;
        
        public ApproveMOTypePropertyResponse() {
        }
        
        public ApproveMOTypePropertyResponse(DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveMOTypePropertyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApproveMOTypePropertyResult;
        
        public ApproveMOTypePropertyResponseBody() {
        }
        
        public ApproveMOTypePropertyResponseBody(string ApproveMOTypePropertyResult) {
            this.ApproveMOTypePropertyResult = ApproveMOTypePropertyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadMOTypePropertyDefineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadMOTypePropertyDefine", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineRequestBody Body;
        
        public LoadMOTypePropertyDefineRequest() {
        }
        
        public LoadMOTypePropertyDefineRequest(DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadMOTypePropertyDefineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public LoadMOTypePropertyDefineRequestBody() {
        }
        
        public LoadMOTypePropertyDefineRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadMOTypePropertyDefineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadMOTypePropertyDefineResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineResponseBody Body;
        
        public LoadMOTypePropertyDefineResponse() {
        }
        
        public LoadMOTypePropertyDefineResponse(DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadMOTypePropertyDefineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadMOTypePropertyDefineResult;
        
        public LoadMOTypePropertyDefineResponseBody() {
        }
        
        public LoadMOTypePropertyDefineResponseBody(string LoadMOTypePropertyDefineResult) {
            this.LoadMOTypePropertyDefineResult = LoadMOTypePropertyDefineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadMOTypeInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadMOTypeInventory", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryRequestBody Body;
        
        public LoadMOTypeInventoryRequest() {
        }
        
        public LoadMOTypeInventoryRequest(DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadMOTypeInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public LoadMOTypeInventoryRequestBody() {
        }
        
        public LoadMOTypeInventoryRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadMOTypeInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadMOTypeInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryResponseBody Body;
        
        public LoadMOTypeInventoryResponse() {
        }
        
        public LoadMOTypeInventoryResponse(DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadMOTypeInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadMOTypeInventoryResult;
        
        public LoadMOTypeInventoryResponseBody() {
        }
        
        public LoadMOTypeInventoryResponseBody(string LoadMOTypeInventoryResult) {
            this.LoadMOTypeInventoryResult = LoadMOTypeInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMOTypeInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMOTypeInventory", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.AddMOTypeInventoryRequestBody Body;
        
        public AddMOTypeInventoryRequest() {
        }
        
        public AddMOTypeInventoryRequest(DB_OPI.wsSYS_LHTC.AddMOTypeInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMOTypeInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public AddMOTypeInventoryRequestBody() {
        }
        
        public AddMOTypeInventoryRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMOTypeInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMOTypeInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.AddMOTypeInventoryResponseBody Body;
        
        public AddMOTypeInventoryResponse() {
        }
        
        public AddMOTypeInventoryResponse(DB_OPI.wsSYS_LHTC.AddMOTypeInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMOTypeInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddMOTypeInventoryResult;
        
        public AddMOTypeInventoryResponseBody() {
        }
        
        public AddMOTypeInventoryResponseBody(string AddMOTypeInventoryResult) {
            this.AddMOTypeInventoryResult = AddMOTypeInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelMOTypeInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelMOTypeInventory", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.DelMOTypeInventoryRequestBody Body;
        
        public DelMOTypeInventoryRequest() {
        }
        
        public DelMOTypeInventoryRequest(DB_OPI.wsSYS_LHTC.DelMOTypeInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelMOTypeInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public DelMOTypeInventoryRequestBody() {
        }
        
        public DelMOTypeInventoryRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelMOTypeInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelMOTypeInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.DelMOTypeInventoryResponseBody Body;
        
        public DelMOTypeInventoryResponse() {
        }
        
        public DelMOTypeInventoryResponse(DB_OPI.wsSYS_LHTC.DelMOTypeInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelMOTypeInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DelMOTypeInventoryResult;
        
        public DelMOTypeInventoryResponseBody() {
        }
        
        public DelMOTypeInventoryResponseBody(string DelMOTypeInventoryResult) {
            this.DelMOTypeInventoryResult = DelMOTypeInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class funCheckDateTimeFormatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="funCheckDateTimeFormat", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatRequestBody Body;
        
        public funCheckDateTimeFormatRequest() {
        }
        
        public funCheckDateTimeFormatRequest(DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class funCheckDateTimeFormatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public funCheckDateTimeFormatRequestBody() {
        }
        
        public funCheckDateTimeFormatRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class funCheckDateTimeFormatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="funCheckDateTimeFormatResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatResponseBody Body;
        
        public funCheckDateTimeFormatResponse() {
        }
        
        public funCheckDateTimeFormatResponse(DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class funCheckDateTimeFormatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string funCheckDateTimeFormatResult;
        
        public funCheckDateTimeFormatResponseBody() {
        }
        
        public funCheckDateTimeFormatResponseBody(string funCheckDateTimeFormatResult) {
            this.funCheckDateTimeFormatResult = funCheckDateTimeFormatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadFunctionPrinterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadFunctionPrinter", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadFunctionPrinterRequestBody Body;
        
        public LoadFunctionPrinterRequest() {
        }
        
        public LoadFunctionPrinterRequest(DB_OPI.wsSYS_LHTC.LoadFunctionPrinterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadFunctionPrinterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public LoadFunctionPrinterRequestBody() {
        }
        
        public LoadFunctionPrinterRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadFunctionPrinterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadFunctionPrinterResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadFunctionPrinterResponseBody Body;
        
        public LoadFunctionPrinterResponse() {
        }
        
        public LoadFunctionPrinterResponse(DB_OPI.wsSYS_LHTC.LoadFunctionPrinterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadFunctionPrinterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadFunctionPrinterResult;
        
        public LoadFunctionPrinterResponseBody() {
        }
        
        public LoadFunctionPrinterResponseBody(string LoadFunctionPrinterResult) {
            this.LoadFunctionPrinterResult = LoadFunctionPrinterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadSystemFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadSystemFunction", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadSystemFunctionRequestBody Body;
        
        public LoadSystemFunctionRequest() {
        }
        
        public LoadSystemFunctionRequest(DB_OPI.wsSYS_LHTC.LoadSystemFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadSystemFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public LoadSystemFunctionRequestBody() {
        }
        
        public LoadSystemFunctionRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadSystemFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadSystemFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadSystemFunctionResponseBody Body;
        
        public LoadSystemFunctionResponse() {
        }
        
        public LoadSystemFunctionResponse(DB_OPI.wsSYS_LHTC.LoadSystemFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadSystemFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadSystemFunctionResult;
        
        public LoadSystemFunctionResponseBody() {
        }
        
        public LoadSystemFunctionResponseBody(string LoadSystemFunctionResult) {
            this.LoadSystemFunctionResult = LoadSystemFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadCFGTERMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadCFGTERM", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadCFGTERMRequestBody Body;
        
        public LoadCFGTERMRequest() {
        }
        
        public LoadCFGTERMRequest(DB_OPI.wsSYS_LHTC.LoadCFGTERMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadCFGTERMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public LoadCFGTERMRequestBody() {
        }
        
        public LoadCFGTERMRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadCFGTERMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadCFGTERMResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.LoadCFGTERMResponseBody Body;
        
        public LoadCFGTERMResponse() {
        }
        
        public LoadCFGTERMResponse(DB_OPI.wsSYS_LHTC.LoadCFGTERMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadCFGTERMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadCFGTERMResult;
        
        public LoadCFGTERMResponseBody() {
        }
        
        public LoadCFGTERMResponseBody(string LoadCFGTERMResult) {
            this.LoadCFGTERMResult = LoadCFGTERMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCFGTERMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCFGTERM", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.AddCFGTERMRequestBody Body;
        
        public AddCFGTERMRequest() {
        }
        
        public AddCFGTERMRequest(DB_OPI.wsSYS_LHTC.AddCFGTERMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCFGTERMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public AddCFGTERMRequestBody() {
        }
        
        public AddCFGTERMRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCFGTERMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCFGTERMResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.AddCFGTERMResponseBody Body;
        
        public AddCFGTERMResponse() {
        }
        
        public AddCFGTERMResponse(DB_OPI.wsSYS_LHTC.AddCFGTERMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCFGTERMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddCFGTERMResult;
        
        public AddCFGTERMResponseBody() {
        }
        
        public AddCFGTERMResponseBody(string AddCFGTERMResult) {
            this.AddCFGTERMResult = AddCFGTERMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCFGTERMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCFGTERM", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.EditCFGTERMRequestBody Body;
        
        public EditCFGTERMRequest() {
        }
        
        public EditCFGTERMRequest(DB_OPI.wsSYS_LHTC.EditCFGTERMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditCFGTERMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public EditCFGTERMRequestBody() {
        }
        
        public EditCFGTERMRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCFGTERMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCFGTERMResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.EditCFGTERMResponseBody Body;
        
        public EditCFGTERMResponse() {
        }
        
        public EditCFGTERMResponse(DB_OPI.wsSYS_LHTC.EditCFGTERMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditCFGTERMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditCFGTERMResult;
        
        public EditCFGTERMResponseBody() {
        }
        
        public EditCFGTERMResponseBody(string EditCFGTERMResult) {
            this.EditCFGTERMResult = EditCFGTERMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelCFGTERMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelCFGTERM", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.DelCFGTERMRequestBody Body;
        
        public DelCFGTERMRequest() {
        }
        
        public DelCFGTERMRequest(DB_OPI.wsSYS_LHTC.DelCFGTERMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelCFGTERMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public DelCFGTERMRequestBody() {
        }
        
        public DelCFGTERMRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelCFGTERMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelCFGTERMResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsSYS_LHTC.DelCFGTERMResponseBody Body;
        
        public DelCFGTERMResponse() {
        }
        
        public DelCFGTERMResponse(DB_OPI.wsSYS_LHTC.DelCFGTERMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelCFGTERMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DelCFGTERMResult;
        
        public DelCFGTERMResponseBody() {
        }
        
        public DelCFGTERMResponseBody(string DelCFGTERMResult) {
            this.DelCFGTERMResult = DelCFGTERMResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsSYSSoapChannel : DB_OPI.wsSYS_LHTC.wsSYSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsSYSSoapClient : System.ServiceModel.ClientBase<DB_OPI.wsSYS_LHTC.wsSYSSoap>, DB_OPI.wsSYS_LHTC.wsSYSSoap {
        
        public wsSYSSoapClient() {
        }
        
        public wsSYSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsSYSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSYSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSYSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.LoadMOTypePropertyResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.LoadMOTypeProperty(DB_OPI.wsSYS_LHTC.LoadMOTypePropertyRequest request) {
            return base.Channel.LoadMOTypeProperty(request);
        }
        
        public string LoadMOTypeProperty(string InXml) {
            DB_OPI.wsSYS_LHTC.LoadMOTypePropertyRequest inValue = new DB_OPI.wsSYS_LHTC.LoadMOTypePropertyRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.LoadMOTypePropertyRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.LoadMOTypePropertyResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).LoadMOTypeProperty(inValue);
            return retVal.Body.LoadMOTypePropertyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.AddMOTypePropertyResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.AddMOTypeProperty(DB_OPI.wsSYS_LHTC.AddMOTypePropertyRequest request) {
            return base.Channel.AddMOTypeProperty(request);
        }
        
        public string AddMOTypeProperty(string InXml) {
            DB_OPI.wsSYS_LHTC.AddMOTypePropertyRequest inValue = new DB_OPI.wsSYS_LHTC.AddMOTypePropertyRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.AddMOTypePropertyRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.AddMOTypePropertyResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).AddMOTypeProperty(inValue);
            return retVal.Body.AddMOTypePropertyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.EditMOTypePropertyResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.EditMOTypeProperty(DB_OPI.wsSYS_LHTC.EditMOTypePropertyRequest request) {
            return base.Channel.EditMOTypeProperty(request);
        }
        
        public string EditMOTypeProperty(string InXml) {
            DB_OPI.wsSYS_LHTC.EditMOTypePropertyRequest inValue = new DB_OPI.wsSYS_LHTC.EditMOTypePropertyRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.EditMOTypePropertyRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.EditMOTypePropertyResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).EditMOTypeProperty(inValue);
            return retVal.Body.EditMOTypePropertyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.DelMOTypePropertyResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.DelMOTypeProperty(DB_OPI.wsSYS_LHTC.DelMOTypePropertyRequest request) {
            return base.Channel.DelMOTypeProperty(request);
        }
        
        public string DelMOTypeProperty(string InXml) {
            DB_OPI.wsSYS_LHTC.DelMOTypePropertyRequest inValue = new DB_OPI.wsSYS_LHTC.DelMOTypePropertyRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.DelMOTypePropertyRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.DelMOTypePropertyResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).DelMOTypeProperty(inValue);
            return retVal.Body.DelMOTypePropertyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.ApproveMOTypeProperty(DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyRequest request) {
            return base.Channel.ApproveMOTypeProperty(request);
        }
        
        public string ApproveMOTypeProperty(string InXml) {
            DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyRequest inValue = new DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.ApproveMOTypePropertyResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).ApproveMOTypeProperty(inValue);
            return retVal.Body.ApproveMOTypePropertyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.LoadMOTypePropertyDefine(DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineRequest request) {
            return base.Channel.LoadMOTypePropertyDefine(request);
        }
        
        public string LoadMOTypePropertyDefine(string InXml) {
            DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineRequest inValue = new DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.LoadMOTypePropertyDefineResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).LoadMOTypePropertyDefine(inValue);
            return retVal.Body.LoadMOTypePropertyDefineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.LoadMOTypeInventory(DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryRequest request) {
            return base.Channel.LoadMOTypeInventory(request);
        }
        
        public string LoadMOTypeInventory(string InXml) {
            DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryRequest inValue = new DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.LoadMOTypeInventoryResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).LoadMOTypeInventory(inValue);
            return retVal.Body.LoadMOTypeInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.AddMOTypeInventoryResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.AddMOTypeInventory(DB_OPI.wsSYS_LHTC.AddMOTypeInventoryRequest request) {
            return base.Channel.AddMOTypeInventory(request);
        }
        
        public string AddMOTypeInventory(string InXml) {
            DB_OPI.wsSYS_LHTC.AddMOTypeInventoryRequest inValue = new DB_OPI.wsSYS_LHTC.AddMOTypeInventoryRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.AddMOTypeInventoryRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.AddMOTypeInventoryResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).AddMOTypeInventory(inValue);
            return retVal.Body.AddMOTypeInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.DelMOTypeInventoryResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.DelMOTypeInventory(DB_OPI.wsSYS_LHTC.DelMOTypeInventoryRequest request) {
            return base.Channel.DelMOTypeInventory(request);
        }
        
        public string DelMOTypeInventory(string InXml) {
            DB_OPI.wsSYS_LHTC.DelMOTypeInventoryRequest inValue = new DB_OPI.wsSYS_LHTC.DelMOTypeInventoryRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.DelMOTypeInventoryRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.DelMOTypeInventoryResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).DelMOTypeInventory(inValue);
            return retVal.Body.DelMOTypeInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.funCheckDateTimeFormat(DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatRequest request) {
            return base.Channel.funCheckDateTimeFormat(request);
        }
        
        public string funCheckDateTimeFormat(string InXml) {
            DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatRequest inValue = new DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.funCheckDateTimeFormatResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).funCheckDateTimeFormat(inValue);
            return retVal.Body.funCheckDateTimeFormatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.LoadFunctionPrinterResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.LoadFunctionPrinter(DB_OPI.wsSYS_LHTC.LoadFunctionPrinterRequest request) {
            return base.Channel.LoadFunctionPrinter(request);
        }
        
        public string LoadFunctionPrinter(string InXml) {
            DB_OPI.wsSYS_LHTC.LoadFunctionPrinterRequest inValue = new DB_OPI.wsSYS_LHTC.LoadFunctionPrinterRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.LoadFunctionPrinterRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.LoadFunctionPrinterResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).LoadFunctionPrinter(inValue);
            return retVal.Body.LoadFunctionPrinterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.LoadSystemFunctionResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.LoadSystemFunction(DB_OPI.wsSYS_LHTC.LoadSystemFunctionRequest request) {
            return base.Channel.LoadSystemFunction(request);
        }
        
        public string LoadSystemFunction(string InXml) {
            DB_OPI.wsSYS_LHTC.LoadSystemFunctionRequest inValue = new DB_OPI.wsSYS_LHTC.LoadSystemFunctionRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.LoadSystemFunctionRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.LoadSystemFunctionResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).LoadSystemFunction(inValue);
            return retVal.Body.LoadSystemFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.LoadCFGTERMResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.LoadCFGTERM(DB_OPI.wsSYS_LHTC.LoadCFGTERMRequest request) {
            return base.Channel.LoadCFGTERM(request);
        }
        
        public string LoadCFGTERM(string InXml) {
            DB_OPI.wsSYS_LHTC.LoadCFGTERMRequest inValue = new DB_OPI.wsSYS_LHTC.LoadCFGTERMRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.LoadCFGTERMRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.LoadCFGTERMResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).LoadCFGTERM(inValue);
            return retVal.Body.LoadCFGTERMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.AddCFGTERMResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.AddCFGTERM(DB_OPI.wsSYS_LHTC.AddCFGTERMRequest request) {
            return base.Channel.AddCFGTERM(request);
        }
        
        public string AddCFGTERM(string InXml) {
            DB_OPI.wsSYS_LHTC.AddCFGTERMRequest inValue = new DB_OPI.wsSYS_LHTC.AddCFGTERMRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.AddCFGTERMRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.AddCFGTERMResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).AddCFGTERM(inValue);
            return retVal.Body.AddCFGTERMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.EditCFGTERMResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.EditCFGTERM(DB_OPI.wsSYS_LHTC.EditCFGTERMRequest request) {
            return base.Channel.EditCFGTERM(request);
        }
        
        public string EditCFGTERM(string InXml) {
            DB_OPI.wsSYS_LHTC.EditCFGTERMRequest inValue = new DB_OPI.wsSYS_LHTC.EditCFGTERMRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.EditCFGTERMRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.EditCFGTERMResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).EditCFGTERM(inValue);
            return retVal.Body.EditCFGTERMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsSYS_LHTC.DelCFGTERMResponse DB_OPI.wsSYS_LHTC.wsSYSSoap.DelCFGTERM(DB_OPI.wsSYS_LHTC.DelCFGTERMRequest request) {
            return base.Channel.DelCFGTERM(request);
        }
        
        public string DelCFGTERM(string InXml) {
            DB_OPI.wsSYS_LHTC.DelCFGTERMRequest inValue = new DB_OPI.wsSYS_LHTC.DelCFGTERMRequest();
            inValue.Body = new DB_OPI.wsSYS_LHTC.DelCFGTERMRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsSYS_LHTC.DelCFGTERMResponse retVal = ((DB_OPI.wsSYS_LHTC.wsSYSSoap)(this)).DelCFGTERM(inValue);
            return retVal.Body.DelCFGTERMResult;
        }
    }
}
