//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_OPI.wsEMS_LHTC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org//wsEMS", ConfigurationName="wsEMS_LHTC.wsEMSSoap")]
    public interface wsEMSSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org//wsEMS 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//wsEMS/LoadEquipmentStateLog", ReplyAction="*")]
        DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogResponse LoadEquipmentStateLog(DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org//wsEMS 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//wsEMS/LoadEquipmentState_Previous", ReplyAction="*")]
        DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousResponse LoadEquipmentState_Previous(DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org//wsEMS 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//wsEMS/Exe_EQPMaterialState_TurnInv", ReplyAction="*")]
        DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvResponse Exe_EQPMaterialState_TurnInv(DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org//wsEMS 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//wsEMS/Exe_EQPMaterialState_TurnEQP", ReplyAction="*")]
        DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPResponse Exe_EQPMaterialState_TurnEQP(DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org//wsEMS 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//wsEMS/LoadEQPMaterialState_Comp", ReplyAction="*")]
        DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompResponse LoadEQPMaterialState_Comp(DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org//wsEMS 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//wsEMS/AddEMSEQSTEventLog", ReplyAction="*")]
        DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogResponse AddEMSEQSTEventLog(DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org//wsEMS 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//wsEMS/AddEMSEQALEventLog", ReplyAction="*")]
        DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogResponse AddEMSEQALEventLog(DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org//wsEMS 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//wsEMS/AddEMSDCRPEventLog", ReplyAction="*")]
        DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogResponse AddEMSDCRPEventLog(DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org//wsEMS 的元素名稱  InXml 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//wsEMS/funChangeStatePrintLabel", ReplyAction="*")]
        DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelResponse funChangeStatePrintLabel(DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadEquipmentStateLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadEquipmentStateLog", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogRequestBody Body;
        
        public LoadEquipmentStateLogRequest() {
        }
        
        public LoadEquipmentStateLogRequest(DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class LoadEquipmentStateLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public LoadEquipmentStateLogRequestBody() {
        }
        
        public LoadEquipmentStateLogRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadEquipmentStateLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadEquipmentStateLogResponse", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogResponseBody Body;
        
        public LoadEquipmentStateLogResponse() {
        }
        
        public LoadEquipmentStateLogResponse(DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class LoadEquipmentStateLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadEquipmentStateLogResult;
        
        public LoadEquipmentStateLogResponseBody() {
        }
        
        public LoadEquipmentStateLogResponseBody(string LoadEquipmentStateLogResult) {
            this.LoadEquipmentStateLogResult = LoadEquipmentStateLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadEquipmentState_PreviousRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadEquipmentState_Previous", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousRequestBody Body;
        
        public LoadEquipmentState_PreviousRequest() {
        }
        
        public LoadEquipmentState_PreviousRequest(DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class LoadEquipmentState_PreviousRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public LoadEquipmentState_PreviousRequestBody() {
        }
        
        public LoadEquipmentState_PreviousRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadEquipmentState_PreviousResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadEquipmentState_PreviousResponse", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousResponseBody Body;
        
        public LoadEquipmentState_PreviousResponse() {
        }
        
        public LoadEquipmentState_PreviousResponse(DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class LoadEquipmentState_PreviousResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadEquipmentState_PreviousResult;
        
        public LoadEquipmentState_PreviousResponseBody() {
        }
        
        public LoadEquipmentState_PreviousResponseBody(string LoadEquipmentState_PreviousResult) {
            this.LoadEquipmentState_PreviousResult = LoadEquipmentState_PreviousResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Exe_EQPMaterialState_TurnInvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Exe_EQPMaterialState_TurnInv", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvRequestBody Body;
        
        public Exe_EQPMaterialState_TurnInvRequest() {
        }
        
        public Exe_EQPMaterialState_TurnInvRequest(DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class Exe_EQPMaterialState_TurnInvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public Exe_EQPMaterialState_TurnInvRequestBody() {
        }
        
        public Exe_EQPMaterialState_TurnInvRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Exe_EQPMaterialState_TurnInvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Exe_EQPMaterialState_TurnInvResponse", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvResponseBody Body;
        
        public Exe_EQPMaterialState_TurnInvResponse() {
        }
        
        public Exe_EQPMaterialState_TurnInvResponse(DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class Exe_EQPMaterialState_TurnInvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Exe_EQPMaterialState_TurnInvResult;
        
        public Exe_EQPMaterialState_TurnInvResponseBody() {
        }
        
        public Exe_EQPMaterialState_TurnInvResponseBody(string Exe_EQPMaterialState_TurnInvResult) {
            this.Exe_EQPMaterialState_TurnInvResult = Exe_EQPMaterialState_TurnInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Exe_EQPMaterialState_TurnEQPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Exe_EQPMaterialState_TurnEQP", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPRequestBody Body;
        
        public Exe_EQPMaterialState_TurnEQPRequest() {
        }
        
        public Exe_EQPMaterialState_TurnEQPRequest(DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class Exe_EQPMaterialState_TurnEQPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public Exe_EQPMaterialState_TurnEQPRequestBody() {
        }
        
        public Exe_EQPMaterialState_TurnEQPRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Exe_EQPMaterialState_TurnEQPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Exe_EQPMaterialState_TurnEQPResponse", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPResponseBody Body;
        
        public Exe_EQPMaterialState_TurnEQPResponse() {
        }
        
        public Exe_EQPMaterialState_TurnEQPResponse(DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class Exe_EQPMaterialState_TurnEQPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Exe_EQPMaterialState_TurnEQPResult;
        
        public Exe_EQPMaterialState_TurnEQPResponseBody() {
        }
        
        public Exe_EQPMaterialState_TurnEQPResponseBody(string Exe_EQPMaterialState_TurnEQPResult) {
            this.Exe_EQPMaterialState_TurnEQPResult = Exe_EQPMaterialState_TurnEQPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadEQPMaterialState_CompRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadEQPMaterialState_Comp", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompRequestBody Body;
        
        public LoadEQPMaterialState_CompRequest() {
        }
        
        public LoadEQPMaterialState_CompRequest(DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class LoadEQPMaterialState_CompRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public LoadEQPMaterialState_CompRequestBody() {
        }
        
        public LoadEQPMaterialState_CompRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadEQPMaterialState_CompResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadEQPMaterialState_CompResponse", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompResponseBody Body;
        
        public LoadEQPMaterialState_CompResponse() {
        }
        
        public LoadEQPMaterialState_CompResponse(DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class LoadEQPMaterialState_CompResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadEQPMaterialState_CompResult;
        
        public LoadEQPMaterialState_CompResponseBody() {
        }
        
        public LoadEQPMaterialState_CompResponseBody(string LoadEQPMaterialState_CompResult) {
            this.LoadEQPMaterialState_CompResult = LoadEQPMaterialState_CompResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEMSEQSTEventLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEMSEQSTEventLog", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogRequestBody Body;
        
        public AddEMSEQSTEventLogRequest() {
        }
        
        public AddEMSEQSTEventLogRequest(DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class AddEMSEQSTEventLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public AddEMSEQSTEventLogRequestBody() {
        }
        
        public AddEMSEQSTEventLogRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEMSEQSTEventLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEMSEQSTEventLogResponse", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogResponseBody Body;
        
        public AddEMSEQSTEventLogResponse() {
        }
        
        public AddEMSEQSTEventLogResponse(DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class AddEMSEQSTEventLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddEMSEQSTEventLogResult;
        
        public AddEMSEQSTEventLogResponseBody() {
        }
        
        public AddEMSEQSTEventLogResponseBody(string AddEMSEQSTEventLogResult) {
            this.AddEMSEQSTEventLogResult = AddEMSEQSTEventLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEMSEQALEventLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEMSEQALEventLog", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogRequestBody Body;
        
        public AddEMSEQALEventLogRequest() {
        }
        
        public AddEMSEQALEventLogRequest(DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class AddEMSEQALEventLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public AddEMSEQALEventLogRequestBody() {
        }
        
        public AddEMSEQALEventLogRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEMSEQALEventLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEMSEQALEventLogResponse", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogResponseBody Body;
        
        public AddEMSEQALEventLogResponse() {
        }
        
        public AddEMSEQALEventLogResponse(DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class AddEMSEQALEventLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddEMSEQALEventLogResult;
        
        public AddEMSEQALEventLogResponseBody() {
        }
        
        public AddEMSEQALEventLogResponseBody(string AddEMSEQALEventLogResult) {
            this.AddEMSEQALEventLogResult = AddEMSEQALEventLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEMSDCRPEventLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEMSDCRPEventLog", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogRequestBody Body;
        
        public AddEMSDCRPEventLogRequest() {
        }
        
        public AddEMSDCRPEventLogRequest(DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class AddEMSDCRPEventLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public AddEMSDCRPEventLogRequestBody() {
        }
        
        public AddEMSDCRPEventLogRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEMSDCRPEventLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEMSDCRPEventLogResponse", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogResponseBody Body;
        
        public AddEMSDCRPEventLogResponse() {
        }
        
        public AddEMSDCRPEventLogResponse(DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class AddEMSDCRPEventLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddEMSDCRPEventLogResult;
        
        public AddEMSDCRPEventLogResponseBody() {
        }
        
        public AddEMSDCRPEventLogResponseBody(string AddEMSDCRPEventLogResult) {
            this.AddEMSDCRPEventLogResult = AddEMSDCRPEventLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class funChangeStatePrintLabelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="funChangeStatePrintLabel", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelRequestBody Body;
        
        public funChangeStatePrintLabelRequest() {
        }
        
        public funChangeStatePrintLabelRequest(DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class funChangeStatePrintLabelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InXml;
        
        public funChangeStatePrintLabelRequestBody() {
        }
        
        public funChangeStatePrintLabelRequestBody(string InXml) {
            this.InXml = InXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class funChangeStatePrintLabelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="funChangeStatePrintLabelResponse", Namespace="http://tempuri.org//wsEMS", Order=0)]
        public DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelResponseBody Body;
        
        public funChangeStatePrintLabelResponse() {
        }
        
        public funChangeStatePrintLabelResponse(DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org//wsEMS")]
    public partial class funChangeStatePrintLabelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string funChangeStatePrintLabelResult;
        
        public funChangeStatePrintLabelResponseBody() {
        }
        
        public funChangeStatePrintLabelResponseBody(string funChangeStatePrintLabelResult) {
            this.funChangeStatePrintLabelResult = funChangeStatePrintLabelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsEMSSoapChannel : DB_OPI.wsEMS_LHTC.wsEMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsEMSSoapClient : System.ServiceModel.ClientBase<DB_OPI.wsEMS_LHTC.wsEMSSoap>, DB_OPI.wsEMS_LHTC.wsEMSSoap {
        
        public wsEMSSoapClient() {
        }
        
        public wsEMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsEMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogResponse DB_OPI.wsEMS_LHTC.wsEMSSoap.LoadEquipmentStateLog(DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogRequest request) {
            return base.Channel.LoadEquipmentStateLog(request);
        }
        
        public string LoadEquipmentStateLog(string InXml) {
            DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogRequest inValue = new DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogRequest();
            inValue.Body = new DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsEMS_LHTC.LoadEquipmentStateLogResponse retVal = ((DB_OPI.wsEMS_LHTC.wsEMSSoap)(this)).LoadEquipmentStateLog(inValue);
            return retVal.Body.LoadEquipmentStateLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousResponse DB_OPI.wsEMS_LHTC.wsEMSSoap.LoadEquipmentState_Previous(DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousRequest request) {
            return base.Channel.LoadEquipmentState_Previous(request);
        }
        
        public string LoadEquipmentState_Previous(string InXml) {
            DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousRequest inValue = new DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousRequest();
            inValue.Body = new DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsEMS_LHTC.LoadEquipmentState_PreviousResponse retVal = ((DB_OPI.wsEMS_LHTC.wsEMSSoap)(this)).LoadEquipmentState_Previous(inValue);
            return retVal.Body.LoadEquipmentState_PreviousResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvResponse DB_OPI.wsEMS_LHTC.wsEMSSoap.Exe_EQPMaterialState_TurnInv(DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvRequest request) {
            return base.Channel.Exe_EQPMaterialState_TurnInv(request);
        }
        
        public string Exe_EQPMaterialState_TurnInv(string InXml) {
            DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvRequest inValue = new DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvRequest();
            inValue.Body = new DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnInvResponse retVal = ((DB_OPI.wsEMS_LHTC.wsEMSSoap)(this)).Exe_EQPMaterialState_TurnInv(inValue);
            return retVal.Body.Exe_EQPMaterialState_TurnInvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPResponse DB_OPI.wsEMS_LHTC.wsEMSSoap.Exe_EQPMaterialState_TurnEQP(DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPRequest request) {
            return base.Channel.Exe_EQPMaterialState_TurnEQP(request);
        }
        
        public string Exe_EQPMaterialState_TurnEQP(string InXml) {
            DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPRequest inValue = new DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPRequest();
            inValue.Body = new DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsEMS_LHTC.Exe_EQPMaterialState_TurnEQPResponse retVal = ((DB_OPI.wsEMS_LHTC.wsEMSSoap)(this)).Exe_EQPMaterialState_TurnEQP(inValue);
            return retVal.Body.Exe_EQPMaterialState_TurnEQPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompResponse DB_OPI.wsEMS_LHTC.wsEMSSoap.LoadEQPMaterialState_Comp(DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompRequest request) {
            return base.Channel.LoadEQPMaterialState_Comp(request);
        }
        
        public string LoadEQPMaterialState_Comp(string InXml) {
            DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompRequest inValue = new DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompRequest();
            inValue.Body = new DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsEMS_LHTC.LoadEQPMaterialState_CompResponse retVal = ((DB_OPI.wsEMS_LHTC.wsEMSSoap)(this)).LoadEQPMaterialState_Comp(inValue);
            return retVal.Body.LoadEQPMaterialState_CompResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogResponse DB_OPI.wsEMS_LHTC.wsEMSSoap.AddEMSEQSTEventLog(DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogRequest request) {
            return base.Channel.AddEMSEQSTEventLog(request);
        }
        
        public string AddEMSEQSTEventLog(string InXml) {
            DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogRequest inValue = new DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogRequest();
            inValue.Body = new DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsEMS_LHTC.AddEMSEQSTEventLogResponse retVal = ((DB_OPI.wsEMS_LHTC.wsEMSSoap)(this)).AddEMSEQSTEventLog(inValue);
            return retVal.Body.AddEMSEQSTEventLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogResponse DB_OPI.wsEMS_LHTC.wsEMSSoap.AddEMSEQALEventLog(DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogRequest request) {
            return base.Channel.AddEMSEQALEventLog(request);
        }
        
        public string AddEMSEQALEventLog(string InXml) {
            DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogRequest inValue = new DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogRequest();
            inValue.Body = new DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsEMS_LHTC.AddEMSEQALEventLogResponse retVal = ((DB_OPI.wsEMS_LHTC.wsEMSSoap)(this)).AddEMSEQALEventLog(inValue);
            return retVal.Body.AddEMSEQALEventLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogResponse DB_OPI.wsEMS_LHTC.wsEMSSoap.AddEMSDCRPEventLog(DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogRequest request) {
            return base.Channel.AddEMSDCRPEventLog(request);
        }
        
        public string AddEMSDCRPEventLog(string InXml) {
            DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogRequest inValue = new DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogRequest();
            inValue.Body = new DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsEMS_LHTC.AddEMSDCRPEventLogResponse retVal = ((DB_OPI.wsEMS_LHTC.wsEMSSoap)(this)).AddEMSDCRPEventLog(inValue);
            return retVal.Body.AddEMSDCRPEventLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelResponse DB_OPI.wsEMS_LHTC.wsEMSSoap.funChangeStatePrintLabel(DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelRequest request) {
            return base.Channel.funChangeStatePrintLabel(request);
        }
        
        public string funChangeStatePrintLabel(string InXml) {
            DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelRequest inValue = new DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelRequest();
            inValue.Body = new DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelRequestBody();
            inValue.Body.InXml = InXml;
            DB_OPI.wsEMS_LHTC.funChangeStatePrintLabelResponse retVal = ((DB_OPI.wsEMS_LHTC.wsEMSSoap)(this)).funChangeStatePrintLabel(inValue);
            return retVal.Body.funChangeStatePrintLabelResult;
        }
    }
}
