//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_OPI.wsCUS_LHTC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsCUS_LHTC.wsCUSSoap")]
    public interface wsCUSSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  HelloWorldResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.HelloWorldResponse HelloWorld(DB_OPI.wsCUS_LHTC.HelloWorldRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  userNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadMaterialUsedState", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateResponse LoadMaterialUsedState(DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  userNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMaterialUsedState", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateResponse InsertMaterialUsedState(DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  TestResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.TestResponse Test(DB_OPI.wsCUS_LHTC.TestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DB_OPI.wsCUS_LHTC.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DB_OPI.wsCUS_LHTC.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadMaterialUsedStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadMaterialUsedState", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateRequestBody Body;
        
        public LoadMaterialUsedStateRequest() {
        }
        
        public LoadMaterialUsedStateRequest(DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadMaterialUsedStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string matLotNo;
        
        public LoadMaterialUsedStateRequestBody() {
        }
        
        public LoadMaterialUsedStateRequestBody(string userNo, string matLotNo) {
            this.userNo = userNo;
            this.matLotNo = matLotNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadMaterialUsedStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadMaterialUsedStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateResponseBody Body;
        
        public LoadMaterialUsedStateResponse() {
        }
        
        public LoadMaterialUsedStateResponse(DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadMaterialUsedStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadMaterialUsedStateResult;
        
        public LoadMaterialUsedStateResponseBody() {
        }
        
        public LoadMaterialUsedStateResponseBody(string LoadMaterialUsedStateResult) {
            this.LoadMaterialUsedStateResult = LoadMaterialUsedStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMaterialUsedStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMaterialUsedState", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateRequestBody Body;
        
        public InsertMaterialUsedStateRequest() {
        }
        
        public InsertMaterialUsedStateRequest(DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMaterialUsedStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string matLotNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string eqpNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string startTimeStr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string expTimeStr;
        
        public InsertMaterialUsedStateRequestBody() {
        }
        
        public InsertMaterialUsedStateRequestBody(string userNo, string matLotNo, string eqpNo, string startTimeStr, string expTimeStr) {
            this.userNo = userNo;
            this.matLotNo = matLotNo;
            this.eqpNo = eqpNo;
            this.startTimeStr = startTimeStr;
            this.expTimeStr = expTimeStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMaterialUsedStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMaterialUsedStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateResponseBody Body;
        
        public InsertMaterialUsedStateResponse() {
        }
        
        public InsertMaterialUsedStateResponse(DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMaterialUsedStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertMaterialUsedStateResult;
        
        public InsertMaterialUsedStateResponseBody() {
        }
        
        public InsertMaterialUsedStateResponseBody(string InsertMaterialUsedStateResult) {
            this.InsertMaterialUsedStateResult = InsertMaterialUsedStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(DB_OPI.wsCUS_LHTC.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(DB_OPI.wsCUS_LHTC.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsCUSSoapChannel : DB_OPI.wsCUS_LHTC.wsCUSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsCUSSoapClient : System.ServiceModel.ClientBase<DB_OPI.wsCUS_LHTC.wsCUSSoap>, DB_OPI.wsCUS_LHTC.wsCUSSoap {
        
        public wsCUSSoapClient() {
        }
        
        public wsCUSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsCUSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCUSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCUSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.HelloWorldResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.HelloWorld(DB_OPI.wsCUS_LHTC.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DB_OPI.wsCUS_LHTC.HelloWorldRequest inValue = new DB_OPI.wsCUS_LHTC.HelloWorldRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.HelloWorldRequestBody();
            DB_OPI.wsCUS_LHTC.HelloWorldResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.LoadMaterialUsedState(DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateRequest request) {
            return base.Channel.LoadMaterialUsedState(request);
        }
        
        public string LoadMaterialUsedState(string userNo, string matLotNo) {
            DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateRequest inValue = new DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateRequestBody();
            inValue.Body.userNo = userNo;
            inValue.Body.matLotNo = matLotNo;
            DB_OPI.wsCUS_LHTC.LoadMaterialUsedStateResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).LoadMaterialUsedState(inValue);
            return retVal.Body.LoadMaterialUsedStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.InsertMaterialUsedState(DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateRequest request) {
            return base.Channel.InsertMaterialUsedState(request);
        }
        
        public string InsertMaterialUsedState(string userNo, string matLotNo, string eqpNo, string startTimeStr, string expTimeStr) {
            DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateRequest inValue = new DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateRequestBody();
            inValue.Body.userNo = userNo;
            inValue.Body.matLotNo = matLotNo;
            inValue.Body.eqpNo = eqpNo;
            inValue.Body.startTimeStr = startTimeStr;
            inValue.Body.expTimeStr = expTimeStr;
            DB_OPI.wsCUS_LHTC.InsertMaterialUsedStateResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).InsertMaterialUsedState(inValue);
            return retVal.Body.InsertMaterialUsedStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.TestResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.Test(DB_OPI.wsCUS_LHTC.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test() {
            DB_OPI.wsCUS_LHTC.TestRequest inValue = new DB_OPI.wsCUS_LHTC.TestRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.TestRequestBody();
            DB_OPI.wsCUS_LHTC.TestResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
    }
}
