//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_OPI.wsCUS_LHTC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsCUS_LHTC.wsCUSSoap")]
    public interface wsCUSSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  HelloWorldResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.HelloWorldResponse HelloWorld(DB_OPI.wsCUS_LHTC.HelloWorldRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  userNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadGlueUsedState", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.LoadGlueUsedStateResponse LoadGlueUsedState(DB_OPI.wsCUS_LHTC.LoadGlueUsedStateRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  userNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGlueReheatData", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.AddGlueReheatDataResponse AddGlueReheatData(DB_OPI.wsCUS_LHTC.AddGlueReheatDataRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  userNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateGlueLifeTimeData", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataResponse UpdateGlueLifeTimeData(DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  userNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadAllGlueReheatingData", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataResponse LoadAllGlueReheatingData(DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  userNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteByMaterialLotNo", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoResponse DeleteByMaterialLotNo(DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  TestResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        DB_OPI.wsCUS_LHTC.TestResponse Test(DB_OPI.wsCUS_LHTC.TestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DB_OPI.wsCUS_LHTC.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DB_OPI.wsCUS_LHTC.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadGlueUsedStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadGlueUsedState", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.LoadGlueUsedStateRequestBody Body;
        
        public LoadGlueUsedStateRequest() {
        }
        
        public LoadGlueUsedStateRequest(DB_OPI.wsCUS_LHTC.LoadGlueUsedStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadGlueUsedStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string matLotNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string reheatStTimeStr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reheatEndTimeStr;
        
        public LoadGlueUsedStateRequestBody() {
        }
        
        public LoadGlueUsedStateRequestBody(string userNo, string matLotNo, string reheatStTimeStr, string reheatEndTimeStr) {
            this.userNo = userNo;
            this.matLotNo = matLotNo;
            this.reheatStTimeStr = reheatStTimeStr;
            this.reheatEndTimeStr = reheatEndTimeStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadGlueUsedStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadGlueUsedStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.LoadGlueUsedStateResponseBody Body;
        
        public LoadGlueUsedStateResponse() {
        }
        
        public LoadGlueUsedStateResponse(DB_OPI.wsCUS_LHTC.LoadGlueUsedStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadGlueUsedStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadGlueUsedStateResult;
        
        public LoadGlueUsedStateResponseBody() {
        }
        
        public LoadGlueUsedStateResponseBody(string LoadGlueUsedStateResult) {
            this.LoadGlueUsedStateResult = LoadGlueUsedStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGlueReheatDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGlueReheatData", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.AddGlueReheatDataRequestBody Body;
        
        public AddGlueReheatDataRequest() {
        }
        
        public AddGlueReheatDataRequest(DB_OPI.wsCUS_LHTC.AddGlueReheatDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGlueReheatDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string matLotNo;
        
        public AddGlueReheatDataRequestBody() {
        }
        
        public AddGlueReheatDataRequestBody(string userNo, string matLotNo) {
            this.userNo = userNo;
            this.matLotNo = matLotNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGlueReheatDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGlueReheatDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.AddGlueReheatDataResponseBody Body;
        
        public AddGlueReheatDataResponse() {
        }
        
        public AddGlueReheatDataResponse(DB_OPI.wsCUS_LHTC.AddGlueReheatDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGlueReheatDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddGlueReheatDataResult;
        
        public AddGlueReheatDataResponseBody() {
        }
        
        public AddGlueReheatDataResponseBody(string AddGlueReheatDataResult) {
            this.AddGlueReheatDataResult = AddGlueReheatDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateGlueLifeTimeDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateGlueLifeTimeData", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataRequestBody Body;
        
        public UpdateGlueLifeTimeDataRequest() {
        }
        
        public UpdateGlueLifeTimeDataRequest(DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateGlueLifeTimeDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string matLotNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lifeStTimeStr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lifeEndTimeStr;
        
        public UpdateGlueLifeTimeDataRequestBody() {
        }
        
        public UpdateGlueLifeTimeDataRequestBody(string userNo, string matLotNo, string lifeStTimeStr, string lifeEndTimeStr) {
            this.userNo = userNo;
            this.matLotNo = matLotNo;
            this.lifeStTimeStr = lifeStTimeStr;
            this.lifeEndTimeStr = lifeEndTimeStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateGlueLifeTimeDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateGlueLifeTimeDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataResponseBody Body;
        
        public UpdateGlueLifeTimeDataResponse() {
        }
        
        public UpdateGlueLifeTimeDataResponse(DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateGlueLifeTimeDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateGlueLifeTimeDataResult;
        
        public UpdateGlueLifeTimeDataResponseBody() {
        }
        
        public UpdateGlueLifeTimeDataResponseBody(string UpdateGlueLifeTimeDataResult) {
            this.UpdateGlueLifeTimeDataResult = UpdateGlueLifeTimeDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadAllGlueReheatingDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadAllGlueReheatingData", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataRequestBody Body;
        
        public LoadAllGlueReheatingDataRequest() {
        }
        
        public LoadAllGlueReheatingDataRequest(DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadAllGlueReheatingDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNo;
        
        public LoadAllGlueReheatingDataRequestBody() {
        }
        
        public LoadAllGlueReheatingDataRequestBody(string userNo) {
            this.userNo = userNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadAllGlueReheatingDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadAllGlueReheatingDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataResponseBody Body;
        
        public LoadAllGlueReheatingDataResponse() {
        }
        
        public LoadAllGlueReheatingDataResponse(DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadAllGlueReheatingDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadAllGlueReheatingDataResult;
        
        public LoadAllGlueReheatingDataResponseBody() {
        }
        
        public LoadAllGlueReheatingDataResponseBody(string LoadAllGlueReheatingDataResult) {
            this.LoadAllGlueReheatingDataResult = LoadAllGlueReheatingDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteByMaterialLotNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteByMaterialLotNo", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoRequestBody Body;
        
        public DeleteByMaterialLotNoRequest() {
        }
        
        public DeleteByMaterialLotNoRequest(DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteByMaterialLotNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string matLotNo;
        
        public DeleteByMaterialLotNoRequestBody() {
        }
        
        public DeleteByMaterialLotNoRequestBody(string userNo, string matLotNo) {
            this.userNo = userNo;
            this.matLotNo = matLotNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteByMaterialLotNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteByMaterialLotNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoResponseBody Body;
        
        public DeleteByMaterialLotNoResponse() {
        }
        
        public DeleteByMaterialLotNoResponse(DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteByMaterialLotNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteByMaterialLotNoResult;
        
        public DeleteByMaterialLotNoResponseBody() {
        }
        
        public DeleteByMaterialLotNoResponseBody(string DeleteByMaterialLotNoResult) {
            this.DeleteByMaterialLotNoResult = DeleteByMaterialLotNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(DB_OPI.wsCUS_LHTC.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public DB_OPI.wsCUS_LHTC.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(DB_OPI.wsCUS_LHTC.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsCUSSoapChannel : DB_OPI.wsCUS_LHTC.wsCUSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsCUSSoapClient : System.ServiceModel.ClientBase<DB_OPI.wsCUS_LHTC.wsCUSSoap>, DB_OPI.wsCUS_LHTC.wsCUSSoap {
        
        public wsCUSSoapClient() {
        }
        
        public wsCUSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsCUSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCUSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCUSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.HelloWorldResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.HelloWorld(DB_OPI.wsCUS_LHTC.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DB_OPI.wsCUS_LHTC.HelloWorldRequest inValue = new DB_OPI.wsCUS_LHTC.HelloWorldRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.HelloWorldRequestBody();
            DB_OPI.wsCUS_LHTC.HelloWorldResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.LoadGlueUsedStateResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.LoadGlueUsedState(DB_OPI.wsCUS_LHTC.LoadGlueUsedStateRequest request) {
            return base.Channel.LoadGlueUsedState(request);
        }
        
        public string LoadGlueUsedState(string userNo, string matLotNo, string reheatStTimeStr, string reheatEndTimeStr) {
            DB_OPI.wsCUS_LHTC.LoadGlueUsedStateRequest inValue = new DB_OPI.wsCUS_LHTC.LoadGlueUsedStateRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.LoadGlueUsedStateRequestBody();
            inValue.Body.userNo = userNo;
            inValue.Body.matLotNo = matLotNo;
            inValue.Body.reheatStTimeStr = reheatStTimeStr;
            inValue.Body.reheatEndTimeStr = reheatEndTimeStr;
            DB_OPI.wsCUS_LHTC.LoadGlueUsedStateResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).LoadGlueUsedState(inValue);
            return retVal.Body.LoadGlueUsedStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.AddGlueReheatDataResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.AddGlueReheatData(DB_OPI.wsCUS_LHTC.AddGlueReheatDataRequest request) {
            return base.Channel.AddGlueReheatData(request);
        }
        
        public string AddGlueReheatData(string userNo, string matLotNo) {
            DB_OPI.wsCUS_LHTC.AddGlueReheatDataRequest inValue = new DB_OPI.wsCUS_LHTC.AddGlueReheatDataRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.AddGlueReheatDataRequestBody();
            inValue.Body.userNo = userNo;
            inValue.Body.matLotNo = matLotNo;
            DB_OPI.wsCUS_LHTC.AddGlueReheatDataResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).AddGlueReheatData(inValue);
            return retVal.Body.AddGlueReheatDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.UpdateGlueLifeTimeData(DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataRequest request) {
            return base.Channel.UpdateGlueLifeTimeData(request);
        }
        
        public string UpdateGlueLifeTimeData(string userNo, string matLotNo, string lifeStTimeStr, string lifeEndTimeStr) {
            DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataRequest inValue = new DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataRequestBody();
            inValue.Body.userNo = userNo;
            inValue.Body.matLotNo = matLotNo;
            inValue.Body.lifeStTimeStr = lifeStTimeStr;
            inValue.Body.lifeEndTimeStr = lifeEndTimeStr;
            DB_OPI.wsCUS_LHTC.UpdateGlueLifeTimeDataResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).UpdateGlueLifeTimeData(inValue);
            return retVal.Body.UpdateGlueLifeTimeDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.LoadAllGlueReheatingData(DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataRequest request) {
            return base.Channel.LoadAllGlueReheatingData(request);
        }
        
        public string LoadAllGlueReheatingData(string userNo) {
            DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataRequest inValue = new DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataRequestBody();
            inValue.Body.userNo = userNo;
            DB_OPI.wsCUS_LHTC.LoadAllGlueReheatingDataResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).LoadAllGlueReheatingData(inValue);
            return retVal.Body.LoadAllGlueReheatingDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.DeleteByMaterialLotNo(DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoRequest request) {
            return base.Channel.DeleteByMaterialLotNo(request);
        }
        
        public string DeleteByMaterialLotNo(string userNo, string matLotNo) {
            DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoRequest inValue = new DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoRequestBody();
            inValue.Body.userNo = userNo;
            inValue.Body.matLotNo = matLotNo;
            DB_OPI.wsCUS_LHTC.DeleteByMaterialLotNoResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).DeleteByMaterialLotNo(inValue);
            return retVal.Body.DeleteByMaterialLotNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DB_OPI.wsCUS_LHTC.TestResponse DB_OPI.wsCUS_LHTC.wsCUSSoap.Test(DB_OPI.wsCUS_LHTC.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test() {
            DB_OPI.wsCUS_LHTC.TestRequest inValue = new DB_OPI.wsCUS_LHTC.TestRequest();
            inValue.Body = new DB_OPI.wsCUS_LHTC.TestRequestBody();
            DB_OPI.wsCUS_LHTC.TestResponse retVal = ((DB_OPI.wsCUS_LHTC.wsCUSSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
    }
}
